development:
  consumer_key: ""
  consumer_secret: ""
  site_url: "https://{church_code}.staging.fellowshiponeapi.com"
  # Store the church code if you are writing a 2nd Party implementation
  # Otherwise, you'll want to ask for the church code from the user
  church_code: ""
  request_token_path: "/v1/Tokens/RequestToken"
  access_token_path: "/v1/Tokens/AccessToken"
  # Use the following for credentials based authentication
  # portal_credential_token_path: "/v1/PortalUser/AccessToken"
  # weblink_credential_token_path: "/v1/WeblinkUser/AccessToken"
  portal_authorize_path: "/v1/PortalUser/Login"
  weblink_authorize_path: "/v1/WeblinkUser/Login"
test:
  consumer_key: ""
  consumer_secret: ""
  site_url: "https://{church_code}.staging.fellowshiponeapi.com"
  request_token_path: "/v1/Tokens/RequestToken"
  access_token_path: "/v1/Tokens/AccessToken"
  # Use the following for credentials based authentication
  # portal_credential_token_path: "/v1/PortalUser/AccessToken"
  # weblink_credential_token_path: "/v1/WeblinkUser/AccessToken"
  portal_authorize_path: "/v1/PortalUser/Login"
  weblink_authorize_path: "/v1/WeblinkUser/Login"
production:
  consumer_key: ""
  consumer_secret: ""
  site_url: "https://{church_code}.fellowshiponeapi.com"
  request_token_path: "/v1/Tokens/RequestToken"
  access_token_path: "/v1/Tokens/AccessToken"
  # Use the following for credentials based authentication
  # portal_credential_token_path: "/v1/PortalUser/AccessToken"
  # weblink_credential_token_path: "/v1/WeblinkUser/AccessToken"
  portal_authorize_path: "/v1/PortalUser/Login"
  weblink_authorize_path: "/v1/WeblinkUser/Login"